// Copyright (c) DevInstance LLC. All rights reserved.

using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;

namespace DevInstance.DevCoreApp.Server.Admin.Services.Core.Account;

/// <summary>
/// The account-page routes that appear inside emailed links.
/// <para>
/// These are string-matched against the <c>@page</c> directives in <c>UI/Pages/Account/</c>. They
/// live here as constants because a link built by hand is a link that silently 404s: the password
/// reset mail spelled its route <c>Account/ResetPassword</c> against a page routed
/// <c>/account/reset-password</c>, which routing does not reconcile — case is ignored, the missing
/// hyphen is not.
/// </para>
/// </summary>
public static class AccountRoutes
{
    public const string ConfirmEmail = "/account/confirm-email";
    public const string ResetPassword = "/account/reset-password";
    public const string Login = "/account/login";
}

/// <summary>
/// Builds absolute links to the account pages for delivery by email — or for an administrator to
/// copy and hand over out of band.
/// <para>
/// <b>This exists so there is exactly one of them.</b> The same invitation URL is built from three
/// places that do not share a request: the New User page, the Edit User page's resend button, and
/// the bulk import handler, which runs on the background queue with no <see cref="HttpContext"/> at
/// all. That last caller is why <see cref="TryBuildBase"/> can return null rather than throw.
/// </para>
/// </summary>
public interface IAccountLinkBuilder
{
    /// <summary>The public origin, or null when it can be resolved from neither config nor request.</summary>
    string? TryBuildBase();

    /// <summary>
    /// The invitation link: confirms the email address and, for a user who has no password yet,
    /// offers the set-password form. Null when the origin cannot be resolved.
    /// </summary>
    string? BuildInvitationLink(Guid applicationUserId, string encodedCode);
}

public sealed class AccountLinkBuilder : IAccountLinkBuilder
{
    /// <summary>
    /// Optional in a request, required outside one. Set it when links must be generated by
    /// background work (bulk user import), or when the public origin is not what the app sees —
    /// behind IIS or any TLS-terminating proxy <c>Request.Scheme</c> can be <c>http</c>.
    /// </summary>
    public const string BaseUrlKey = "App:BaseUrl";

    private readonly IConfiguration configuration;
    private readonly IHttpContextAccessor httpContextAccessor;

    public AccountLinkBuilder(IConfiguration configuration, IHttpContextAccessor httpContextAccessor)
    {
        this.configuration = configuration;
        this.httpContextAccessor = httpContextAccessor;
    }

    public string? TryBuildBase()
    {
        var configured = configuration[BaseUrlKey];
        if (!string.IsNullOrWhiteSpace(configured))
        {
            return configured.TrimEnd('/');
        }

        var request = httpContextAccessor.HttpContext?.Request;
        if (request == null)
        {
            return null;
        }

        return $"{request.Scheme}://{request.Host}";
    }

    public string? BuildInvitationLink(Guid applicationUserId, string encodedCode)
    {
        var origin = TryBuildBase();
        if (origin == null)
        {
            return null;
        }

        return $"{origin}{AccountRoutes.ConfirmEmail}?userId={Uri.EscapeDataString(applicationUserId.ToString())}&code={Uri.EscapeDataString(encodedCode)}";
    }
}
