# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default

variables:
  buildConfiguration: 'Release'
  solution: '**/*.slnx'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 10.x'
  inputs:
    version: 10.x

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'

# Step 2: Build the Solution
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

# Step 3: Run Unit Tests
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '**/tests/**/*[Tt]ests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore'
  continueOnError: false

