<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>DevInstance.DevCoreApp.Client.Services.Tests</AssemblyName>
        <RootNamespace>DevInstance.DevCoreApp.Client.Services.Tests</RootNamespace>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\src\Client\Client.Services\Client.Services.csproj" />
      <ProjectReference Include="..\..\Shared\TestUtils\TestUtils.csproj" />
    </ItemGroup>

</Project>
