<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>DevInstance.DevCoreApp.Shared.Model</AssemblyName>
    <RootNamespace>DevInstance.DevCoreApp.Shared.Model</RootNamespace>
    <Configurations>Debug;Release;ServiceMocks</Configurations>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="DevInstance.BlazorToolkit" Version="10.5.0" />
	  <PackageReference Include="DevInstance.WebServiceToolkit.Common" Version="10.3.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
</Project>
